


encrypt-type: 0  # 0:standard, 1:guomi
group-channel-connections-config:
  all-channel-connections:
  - group-id: 1  #group ID
    connections-str:
                    - 127.0.0.1:20200  # node listen_ip:channel_listen_port

channel-service:
  group-id: 1 # The specified group to which the SDK connects
  org-id: agency # agency name

user-key:
  user-key:  # user key 

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supplychain?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: test
    password: Hrd6plus
mybatis:
  mapperLocations: classpath:/mapper/*.xml
server:
  port: 8088
